apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-app
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo-app
  template:
    metadata:
      labels:
        app: kubernetes-demo-app
    spec:
      containers:
      - name: kubernetes-demo-app
        image: fatimaghafoor/kubernetes-demo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"